version: "3.8"
services:
  pixelation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Place
      - PIXELATION_PLACE_WIDTH=30
      - PIXELATION_PLACE_HEIGHT=30
    container_name: web_app_template
    restart: always
    ports:
      - 3000:3000
